---
ID: "b39eacf1-18b6-475f-adc8-3aac06098622"
Parent: "d5a78a1f-d638-4f07-827c-db031344b614"
Template: "fd2059fd-6043-4dfe-8c04-e2437ce87634"
Path: "/sitecore/content/skate-park/skate-park/Presentation/Partial Designs/Product Content"
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: "product-content"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{B973E540-F4EB-43D8-BA1A-06D7B91086C8}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "48f98ae8-2741-422c-bed1-cf3e7672c6d6"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{613A372C-904C-40E4-87F0-CB604D0D0842}"
              p:before="*"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles=%7C%7B552BB9F7-EABC-4CDB-9D18-CFF60CCF5C23%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{96DF61B9-C9C5-4B7E-9261-8A0CAC09E45A}"
              p:after="r[@uid='{613A372C-904C-40E4-87F0-CB604D0D0842}']"
              s:id="{3836D951-BB14-43AC-9231-649B7F245DC5}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BED4E41BB-079B-483F-9FAB-6566CFE90FA3%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="/headless-main/container-1" />
            <r
              uid="{90D71D42-6B71-4962-A8D3-96116C6BB0E6}"
              p:after="*[1=2]"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BE966A5C7-ACF4-4BE4-93F9-63BFE3AE2A8E%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
              s:ph="/headless-main/container-1" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251218T055406Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f6721ab4-51b8-4e2e-8d3c-bf8c2c1251eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251218T055611Z
